{% set name = "shadowenv" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Shopify/shadowenv/archive/{{ version }}.tar.gz
  sha256: 6cfdecb4f9684d0c536ab88847da5f314145f19bd504a8f13b59adf2966bb05c

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - shadowenv --help

about:
  home: https://github.com/Shopify/shadowenv
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Reversible directory-local environment variable manipulations
  dev_url: https://github.com/Shopify/shadowenv

extra:
  recipe-maintainers:
    - danielnachun
