context:
  version: "3.4.0"

package:
  name: shadowenv
  version: ${{ version }}

source:
  url: https://github.com/Shopify/shadowenv/archive/${{ version }}.tar.gz
  sha256: 86313a5022a8e897ceb52a51479fa7a921e44cd520cf04d111ba711684791e44

build:
  number: 1
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - shadowenv --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Reversible directory-local environment variable manipulations
  homepage: https://github.com/Shopify/shadowenv
  repository: https://github.com/Shopify/shadowenv

extra:
  recipe-maintainers:
    - danielnachun
