context:
  version: "3.3.1"

package:
  name: shadowenv
  version: ${{ version }}

source:
  url: https://github.com/Shopify/shadowenv/archive/${{ version }}.tar.gz
  sha256: 726c2a655749213cd7f0efe9dca199f65c11b58774c5550ea4834d5b2334b27c

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - shadowenv --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Reversible directory-local environment variable manipulations
  homepage: https://github.com/Shopify/shadowenv
  repository: https://github.com/Shopify/shadowenv

extra:
  recipe-maintainers:
    - danielnachun
